const data = [
  "7-Zip 24.08 (x64)",
  "AMD Software",
  "Dell Peripheral Manager",
  "Docker Desktop",
  "Git",
  "Mozilla Firefox (x64 pt-BR)",
  "Mozilla Maintenance Service",
  "Notepad++ (64-bit x64)",
  "ONLYOFFICE Desktop Editors 7.3 (x64)",
  "Speccy",
  "Tomb Raider",
  "Cuphead",
  "Hollow Knight",
  "Pixel Strike 3D",
  "WinRAR 7.01 (64-bit)",
  "AMD DVR64",
  "Microsoft.NET.Sdk.Maui.Manifest-8.0.100 (x64)",
  "AMD Settings",
  "Microsoft ASP.NET Core 8.0.8 Shared Framework (x64)",
  "Python 3.11.4 Development Libraries (64-bit)",
  "Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219",
  "FortiClient VPN",
  "Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.61030",
  "Microsoft.NET.Sdk.Aspire.Manifest-8.0.100 (x64)",
  "Agente Track",
  "Microsoft .NET Host - 8.0.8 (x64)",
  "Java(TM) SE Development Kit 21.0.2 (64-bit)",
  "Microsoft Windows Desktop Targeting Pack - 8.0.8 (x64)",
  "Microsoft.NET.Workload.Mono.Toolchain.net7.Manifest (x64)",
  "Branding64",
  "PuTTY release 0.78 (64-bit)",
  "Microsoft.NET.Workload.Emscripten.net7.Manifest (x64)",
  "Python 3.11.4 Test Suite (64-bit)",
  "Microsoft.NET.Sdk.tvOS.Manifest-8.0.100 (x64)",
  "Microsoft Visual C++ 2022 X64 Additional Runtime - 14.40.33810",
  "Microsoft .NET 8.0 Templates 8.0.401 (x64)",
  "Microsoft System CLR Types for SQL Server 2019",
  "Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161",
  "Microsoft Windows Desktop Runtime - 8.0.8 (x64)",
  "vs_devenx64vmsi",
  "Microsoft.NET.Sdk.iOS.Manifest-8.0.100 (x64)",
  "VS JIT Debugger",
  "Bonjour",
  "Microsoft Visual Studio Installer",
  "Microsoft .NET 8.0 Templates 8.0.400 (x64)",
  "Microsoft.NET.Sdk.tvOS.Manifest-8.0.100 (x64)",
  "Python 3.11.4 Add to Path (64-bit)",
  "Python 3.11.4 Standard Library (64-bit)",
  "Microsoft .NET Host FX Resolver - 8.0.8 (x64)",
  "Microsoft.NET.Sdk.Android.Manifest-8.0.100 (x64)",
  "Microsoft.NET.Sdk.MacCatalyst.Manifest-8.0.100 (x64)",
  "Microsoft .NET Toolset 8.0.400 (x64)",
  "Microsoft.NET.Sdk.Maui.Manifest-8.0.100 (x64)",
  "Python 3.11.4 Utility Scripts (64-bit)",
  "Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.21005",
  "DiagnosticsHub_CollectionService",
  "OpenVPN 2.6.5-I001 amd64",
  "Microsoft.NET.Sdk.macOS.Manifest-8.0.100 (x64)",
  "Microsoft .NET Runtime - 8.0.8 (x64)",
  "Microsoft.NET.Workload.Emscripten.net6.Manifest (x64)",
  "Microsoft .NET AppHost Pack - 8.0.8 (x64)",
  "Microsoft ASP.NET Core 8.0.8 Targeting Pack (x64)",
  "Microsoft.NET.Sdk.iOS.Manifest-8.0.100 (x64)",
  "Python 3.11.4 Tcl/Tk Support (64-bit)",
  "Microsoft .NET Standard Targeting Pack - 2.1.0 (x64)",
  "Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.21005",
  "icecap_collection_x64",
  "Windows Subsystem for Linux",
  "AMD WVR64",
  "Adobe Acrobat (64-bit)",
  "vs_minshellinteropx64msi",
  "Microsoft.NET.Sdk.Android.Manifest-8.0.100 (x64)",
  "Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.40.33810",
  "spacedesk Windows DRIVER",
  "Microsoft.NET.Sdk.macOS.Manifest-8.0.100 (x64)",
  "Microsoft Update Health Tools",
  "Microsoft.NET.Workload.Mono.Toolchain.net6.Manifest (x64)",
  "Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61030",
  "Microsoft .NET SDK 8.0.400 (x64) from Visual Studio",
  "Python 3.11.4 pip Bootstrap (64-bit)",
  "Python 3.11.4 Executables (64-bit)",
  "Microsoft .NET Targeting Pack - 8.0.8 (x64)",
  "vs_communityx64msi",
  "vs_minshellx64msi",
  "Microsoft.NET.Workload.Emscripten.Current.Manifest (x64)",
  "Microsoft.NET.Workload.Mono.Toolchain.Current.Manifest (x64)",
  "Microsoft .NET AppHost Pack - 8.0.8 (x64_x86)",
  "Microsoft.NET.Sdk.MacCatalyst.Manifest-8.0.100 (x64)",
  "Flameshot",
  "Node.js",
  "Microsoft .NET Toolset 8.0.401 (x64)",
  "Microsoft.NET.Sdk.Aspire.Manifest-8.0.100 (x64)",
  "VS Script Debugging Common",
  "IntelliTraceProfilerProxy",
  "Epic Games Launcher Prerequisites (x64)",
  "Python 3.11.4 Documentation (64-bit)",
  "Microsoft .NET AppHost Pack - 8.0.8 (x64_arm64)",
  "MongoDB 8.0.0 2008R2Plus SSL (64 bit)",
  "Python 3.11.4 Core Interpreter (64-bit)",
  "MSI Afterburner 4.6.5",
  "AnyDesk",
  "Visual Studio Community 2022",
  "Google Chrome",
  "Inno Setup versão 6.3.3",
  "Microsoft Edge",
  "Microsoft Edge Update",
  "Microsoft Edge WebView2 Runtime",
  "Nmap 7.95",
  "Npcap",
  "OBS Studio",
  "Pritunl Client",
  "PunkBuster Services",
  "RivaTuner Statistics Server 7.3.4",
  "Steam",
  "WinSCP 6.1",
  "WO Mic Client",
  "Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501",
  "Administrative Templates (.admx) for Windows 11 September 2022 Update",
  "Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.40.33810",
  "Sophos Connect",
  "Microsoft .NET Framework 4.7.2 Targeting Pack",
  "vs_CoreEditorFonts",
  "Microsoft .NET Framework Cumulative Intellisense Pack for Visual Studio (ENU)",
  "Microsoft GameInput",
  "Python Launcher",
  "vs_minshellsharedmsi",
  "Pacote de Direcionamento do Microsoft .NET Framework 4.8 (Português (Brasil))",
  "icecap_collectionresources",
  "Microsoft .NET Host - 8.0.8 (x86)",
  "Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.61030",
  "vs_tipsmsi",
  "vs_minshellmsires",
  "Microsoft ASP.NET Core 8.0.8 Targeting Pack (x86)",
  "Launcher Prerequisites (x64)",
  "vs_vswebprotocolselectormsi",
  "Microsoft Visual C++ 2015-2022 Redistributable (x86) - 14.40.33810",
  "Pacote de Direcionamento do Microsoft .NET Framework 4.7.2 (Português (Brasil))",
  "Titanfall™ 2",
  "icecap_collectionresourcesx64",
  "Epic Online Services",
  "vs_filehandler_amd64",
  "icecap_collection_neutral",
  "Microsoft .NET Runtime - 8.0.8 (x86)",
  "Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.40.33810",
  "vs_filehandler_x86",
  "Microsoft Visual C++ 2022 X86 Additional Runtime - 14.40.33810",
  "Microsoft .NET Host FX Resolver - 8.0.8 (x86)",
  "vs_communitymsires",
  "vs_clickoncesigntoolmsi",
  "vs_minshellmsires",
  "icecap_collectionresourcesx64",
  "Microsoft ASP.NET Core 8.0.8 Shared Framework (x86)",
  "Microsoft TestPlatform SDK Local Feed",
  "Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.40664",
  "vs_minshellinteropsharedmsi",
  "vcpp_crt.redist.clickonce",
  "vs_clickoncebootstrappermsi",
  "Microsoft Windows Desktop Targeting Pack - 8.0.8 (x86)",
  "Microsoft .NET Framework 4.8 SDK",
  "Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17",
  "Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161",
  "vs_SQLClickOnceBootstrappermsi",
  "Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.40664",
  "vs_communitysharedmsi",
  "Microsoft .NET Framework 4.8 Targeting Pack (ENU)",
  "Microsoft Visual Studio Setup WMI Provider",
  "vcpp_crt.redist.clickonce",
  "vs_githubprotocolhandlermsi",
  "SDK do Microsoft .NET Framework 4.8 (Português (Brasil))",
  "Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61030",
  "Microsoft .NET Framework 4.7.2 Targeting Pack (ENU)",
  "Microsoft .NET SDK 8.0.401 (x64)",
  "Epic Games Launcher",
  "vs_clickoncebootstrappermsires",
  "Microsoft .NET Framework 4.8 Targeting Pack",
  "Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61030",
  "ClickOnce Bootstrapper Package for Microsoft .NET Framework",
  "VS Immersive Activate Helper",
  "IntelliTraceProfilerProxy",
  "Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.61030",
  "vs_communitymsires",
  "Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.40664",
  "vs_vswebprotocolselectormsires",
  "icecap_collectionresources",
  "Microsoft Visual Studio Setup Configuration",
  "Microsoft .NET Targeting Pack - 8.0.8 (x86)",
  "Entity Framework 6.2.0 Tools  for Visual Studio 2022",
  "Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219",
  "Realtek High Definition Audio Driver",
  "Pacote IntelliSense Cumulativo do Microsoft .NET Framework para Visual Studio (Português do Brasil)",
  "vs_FileTracker_Singleton",
  "vs_BlendMsi",
  "vs_devenvsharedmsi",
  "Microsoft Windows Desktop Runtime - 8.0.8 (x86)",
];

function filterSoftwareNames(data) {
  const regex = /^(\S+\s+\S+\s+[A-Z]\S*)(?:\s|$)/;
  return data.map((item) => {
    const match = item.match(regex);
    console.log(match);
    return match ? match[1] : item.split(" ").splice(0, 3).join(" ");
  });
}
filterSoftwareNames(data);
