export const mockDataTest = {
  cpu_usage: 75.3,
  ram_usage: 87.8,
  cpu_temp: 68,
  disk_health: 85,
  free_disk_space: 94,
  total_disk_space: 240,
};

export const mockHistoryData = [
  {
    cpu_usage: 40,
    ram_usage: 86,
    cpu_temp: 65,
    free_disk_space: 120,
    total_disk_space: 240,
    day: "Sab",
  },
  {
    cpu_usage: 0,
    ram_usage: 0,
    cpu_temp: 80,
    free_disk_space: 80,
    total_disk_space: 240,
    day: "Ter",
  },
  {
    cpu_usage: 70,
    ram_usage: 98,
    cpu_temp: 85,
    free_disk_space: 120,
    total_disk_space: 240,
    day: "Dom",
  },
  {
    cpu_usage: 80,
    ram_usage: 0,
    cpu_temp: 70,
    free_disk_space: 110,
    total_disk_space: 240,
    day: "Seg",
  },
  {
    cpu_usage: 30,
    ram_usage: 70,
    cpu_temp: 75,
    free_disk_space: 160,
    total_disk_space: 240,
    day: "Sab",
  },
  {
    cpu_usage: 81,
    ram_usage: 48,
    cpu_temp: 80,
    free_disk_space: 80,
    total_disk_space: 240,
    day: "Seg",
  },
  {
    cpu_usage: 70,
    ram_usage: 92,
    cpu_temp: 85,
    free_disk_space: 120,
    total_disk_space: 240,
    day: "Ter",
  },
  {
    cpu_usage: 95,
    ram_usage: 35,
    cpu_temp: 80,
    free_disk_space: 80,
    total_disk_space: 240,
    day: "Qua",
  },
  {
    cpu_usage: 70,
    ram_usage: 92,
    cpu_temp: 85,
    free_disk_space: 120,
    total_disk_space: 240,
    day: "Qui",
  },
  {
    cpu_usage: 81,
    ram_usage: 48,
    cpu_temp: 80,
    free_disk_space: 80,
    total_disk_space: 240,
    day: "Sex",
  },
  {
    cpu_usage: 70,
    ram_usage: 92,
    cpu_temp: 85,
    free_disk_space: 120,
    total_disk_space: 240,
    day: "Dom",
  },
];
